# docker-compose.yml


services:
  speaches:
    build: .
    container_name: speaches-custom
    ports:
      # Connect to this port from outside
      - "8005:8005"
    volumes:
      - speaches_data:/home/ubuntu/.cache
    environment:
      # Port configuration
      - UVICORN_PORT=8005


      # Close the UI
      - ENABLE_UI=false

      # Log level (debug, info, warning, error, critical)
      - LOG_LEVEL=info

      # Telemetry disabled
      - DO_NOT_TRACK=1
      - GRADIO_ANALYTICS_ENABLED=False
      - DISABLE_TELEMETRY=1
      - HF_HUB_DISABLE_TELEMETRY=1

    restart: unless-stopped

    # Support for GPU usage
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  speaches_data:
